# Generated by Django 3.2.20 on 2025-06-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(null=True, verbose_name='手机号'),
        ),
    ]
